language: python
python:
  - "3.6"
node_js:
  - "7"
install:
  - pip install -r backend/requirements.txt
  - pip install coveralls
  - npm install
services:
  - postgresql
before_script:
    - psql -c 'CREATE DATABASE stelios_backend;' -U postgres
    - python backend/manage.py makemigrations quiz
    - python backend/manage.py makemigrations wiki
    - python backend/manage.py makemigrations profiles
    - python backend/manage.py migrate
script:
  - cd backend/
  - coverage run --branch --source=quiz,wiki,profiles ./manage.py test
  - cd ../frontend/
  - npm test
after_success:
  coveralls
