language: python
python:
  - "3.6"
install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install 7.5.0
  - node -v
  - npm -v
  - cd frontend/
  - npm install
  - cd ../backend/
  - pip install -r requirements.txt
  - pip install coveralls
  - cd ..
services:
  - postgresql
before_script:
    - psql -c 'CREATE DATABASE stelios_backend;' -U postgres
    - python backend/manage.py makemigrations quiz
    - python backend/manage.py makemigrations wiki
    - python backend/manage.py makemigrations profiles
    - python backend/manage.py migrate
script:
  - cd backend/
  - coverage run --branch --source=quiz,wiki,profiles ./manage.py test
  - cd ../frontend/
  - npm test
  - cd ..
after_success:
  coveralls
