install:
- rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm
  && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm
  install 7.5.0
- cd frontend/
- npm install -g npm@latest
- npm install
- cd ../backend/
- pip3 install -r requirements.txt
- pip3 install coveralls
- cd ..
services:
- postgresql
before_script:
- psql -c 'CREATE DATABASE stelios_backend;' -U postgres
- python3 backend/manage.py makemigrations quiz
- python3 backend/manage.py makemigrations wiki
- python3 backend/manage.py makemigrations profiles
- python3 backend/manage.py migrate
script:
- cd backend/
- coverage run --branch --source=quiz,wiki,profiles ./manage.py test
- cd ../frontend/
- npm test
- cd ..
after_succes:
- coveralls
addons:
  ssh_known_hosts: stelios.no
before_deploy:
- openssl aes-256-cbc -K $encrypted_41c5c3ce1f10_key -iv $encrypted_41c5c3ce1f10_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- ls
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script:
  - ssh pekka@stelios.no 'cd /home/stelios/; git stash; git checkout continuous_integration;
    git pull; cd backend/; source backendenv/bin/activate; python manage.py makemigrations
    wiki; python manage.py makemigrations quiz; python manage.py makemigrations profiles;
    python manage.py migrate; cd ../frontend/; npm install; npm run build; cp -R /home/stelios/frontend/build/*
    /var/www/stelios.no/html/;'
  on:
    branch: continuous_integration
after_deploy:
- rm -f /tmp/deploy_rsa
- ssh pekka@stelios.no 'sudo reboot now'
notifications:
  slack:
    secure: TZjkF1ouaLkKYg1oNA/ZLPP70T7XC6lQmc6aewpNn/qh0D8TFrot9SqtfCLdFyt/CeocUdLoi4hHpQVsuN6Hr1AcNN1lVfrrjsJdO4uPCbiUc8znob8yrTU3+Qw9KrO5vaVMV+omA11MmiEMv74ACNqUnBBU+tPHs2cmo9Pjy2ocPl6BGoquUG5oJT5wFANmmK7MgbRoAsr/qztFeBeOIYRSdrZRl/5s5u/EI2J6oLdreVBakjhLL6OwjJBBs6VopuEeETvuaUAVYuWKqVNcGDmWGtPgxwdu3TV0y5hoCFl854A8NgVcsij2GncgQfutNADNBqs5jzhooAe7s5Gu67CFSuBKK+zG/a4nTG+033IsjmHEoKEhyvPsdAJyt3xVBjjHxYazGEuvOX1Z4x8xo4fsXF7b6xGxxcvDY/+4uXDT8oZtoTLTPDnmaDqJqxSr+7E2wVk/xziOcUX/c0UMaQDI9FBFfXStpETuzuKjuck5gglWFj/GYhehmK5x+7dcJwx9Cpawz/tKfaAKFzP48qa0M/qdh4xbcYxSa1Xn3TG7acBY0dhzcyqGY1z48dwpKnEZdjsMS+ZGhhY2Ry3bfSfdMm38nZ2oW4848F6dRguopVDg6CwsnszD4rD3YkrsvQNoDbvMdUXhKFI0NqPKKji0yjcT8wNvrtyHLHy2XWg=
