language: python
python:
  - '3.6'
install:
  - cd backend/
  - pip install -r requirements.txt
  - cd ..
script:
  - cd backend/
  - cd ..
addons:
  ssh_known_hosts: stelios.no
before_deploy:
  - openssl aes-256-cbc -K $encrypted_41c5c3ce1f10_key -iv $encrypted_41c5c3ce1f10_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - ls
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script:
    - ssh pekka@stelios.no 'cd /home/stelios/; git stash; git checkout continuous_integration; git pull; cd backend/; source backendenv/bin/activate; python manage.py makemigrations wiki; python manage.py makemigrations quiz; python manage.py makemigrations profiles; python manage.py migrate; sudo reboot now'
    # cd frontend/; npm install; npm run build; cp -R /home/stelios/frontend/build/* /var/www/stelios.no/html/;
    #rsync -r --delete-after --quiet /home/travis/build/pu53/stelios/frontend/html pekka@stelios.no:/var/www/stelios.no/
  on:
    branch: continuous_integration
after_deploy: rm -f /tmp/deploy_rsa
