language: python
python:
- '3.6'
install:
- rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm
  && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm
  install 7.5.0
- node -v
- npm -v
- cd frontend/
- npm install
- cd ../backend/
- pip install -r requirements.txt
- pip install coveralls
- cd ..
services:
- postgresql
before_script:
- psql -c 'CREATE DATABASE stelios_backend;' -U postgres
- python backend/manage.py makemigrations quiz
- python backend/manage.py makemigrations wiki
- python backend/manage.py makemigrations profiles
- python backend/manage.py migrate
script:
- cd backend/
- coverage run --branch --source=quiz,wiki,profiles ./manage.py test
- cd ../frontend/
- npm test
- npm run build
- mv build html
- cd ..
addons:
  ssh_known_hosts: stelios.no
after_success:
  - coveralls
  - openssl aes-256-cbc -K $encrypted_41c5c3ce1f10_key -iv $encrypted_41c5c3ce1f10_iv -in deploy_rsa.enc -out deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
  provider: script
  skip_cleanup: true
  script:
    - rsync -r --delete-after --quiet /home/travis/build/pu53/stelios/frontend/html pekka@stelios.no:/var/www/stelios.no/
  on:
    branch: continuous_integration
