# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(default='', max_length=140),
        ),
        migrations.AlterField(
            model_name='subtopic',
            name='name',
            field=models.CharField(default='', max_length=140),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(default='', max_length=140),
        ),
    ]
