# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 14:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0003_auto_20170221_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='subtopic',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='created_by',
        ),
    ]
