# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0004_auto_20170221_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtopic',
            name='topics',
            field=models.ManyToManyField(to='wiki.Topic'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='subject',
            field=models.ManyToManyField(to='wiki.Subject'),
        ),
    ]
