# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0005_auto_20170221_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtopic',
            name='name',
            field=models.CharField(default='kappa', max_length=140),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(default='kappa', max_length=140),
        ),
    ]
