# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0007_auto_20170221_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtopic',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='topics', to='wiki.Topic'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='subject',
            field=models.ManyToManyField(blank=True, related_name='subjects', to='wiki.Subject'),
        ),
    ]
