# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0008_auto_20170221_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtopic',
            name='topics',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='subject',
        ),
        migrations.AddField(
            model_name='subject',
            name='topic',
            field=models.ManyToManyField(blank=True, to='wiki.Topic'),
        ),
        migrations.AddField(
            model_name='topic',
            name='sub_topics',
            field=models.ManyToManyField(blank=True, related_name='topics', to='wiki.SubTopic'),
        ),
    ]
