# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0009_auto_20170221_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='topic',
            field=models.ManyToManyField(blank=True, related_name='topics', to='wiki.Topic'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='sub_topics',
            field=models.ManyToManyField(blank=True, related_name='subtopics', to='wiki.SubTopic'),
        ),
    ]
