# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0010_auto_20170221_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(default='fugletitting', max_length=140),
        ),
    ]
