# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0011_auto_20170221_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='sub_topics',
        ),
        migrations.AddField(
            model_name='subtopic',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='topics', to='wiki.Topic'),
        ),
        migrations.AddField(
            model_name='topic',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='subjects', to='wiki.Subject'),
        ),
    ]
