# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 11:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wiki', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=1000)),
                ('pub_date', models.DateTimeField(verbose_name='Date published')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('deadline', models.DateTimeField(default=None, verbose_name='Deadline')),
                ('subject', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='wiki.Subject')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ManyToManyField(related_name='quiz_question', to='quiz.Quiz'),
        ),
        migrations.AddField(
            model_name='question',
            name='subtopic',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='wiki.Subtopic'),
        ),
        migrations.AddField(
            model_name='choice',
            name='correct_answer_to',
            field=models.ManyToManyField(blank=True, default=None, related_name='correct_answer_to', to='quiz.Question'),
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ManyToManyField(related_name='question_choice', to='quiz.Question'),
        ),
        migrations.AddField(
            model_name='choice',
            name='subtopic',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='wiki.Subtopic'),
        ),
    ]
