# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 01:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct', models.BooleanField(default=False)),
                ('QuizID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Answer_Quiz', to='quiz.Quiz')),
                ('choiceID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Answer_Choice', to='quiz.Choice')),
                ('questionID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Answer_Question', to='quiz.Question')),
                ('userID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Answer_User', to='profiles.Profile')),
            ],
        ),
    ]
