# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 22:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='subtopic',
        ),
        migrations.RemoveField(
            model_name='question',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='correct_answer_to',
        ),
        migrations.AddField(
            model_name='choice',
            name='correct_answer_to',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='correct_answer_to', to='quiz.Question'),
        ),
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='question_choice', to='quiz.Question'),
        ),
        migrations.RemoveField(
            model_name='question',
            name='quiz',
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_question', to='quiz.Quiz'),
        ),
        migrations.RemoveField(
            model_name='question',
            name='subtopic',
        ),
        migrations.AddField(
            model_name='question',
            name='subtopic',
            field=models.ManyToManyField(default=None, to='wiki.Subtopic'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
