# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-19 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='sub_topic',
            new_name='subtopic',
        ),
        migrations.AddField(
            model_name='choice',
            name='subtopic',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='deadline',
            field=models.DateTimeField(verbose_name='Deadline'),
        ),
    ]
