# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='deadline',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Deadline'),
        ),
    ]
