# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 01:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='QuizID',
            new_name='quizID',
        ),
    ]
