# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 22:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20170323_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='correct_answer_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='correct_answer_to', to='quiz.Question'),
        ),
    ]
