# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-22 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20170319_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='deadline',
            field=models.DateTimeField(default=None, verbose_name='Deadline'),
        ),
    ]
