# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20170324_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='subtopic',
            field=models.ManyToManyField(default=None, related_name='subtopic_question', to='wiki.Subtopic'),
        ),
    ]
