# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='quizes',
            field=models.ManyToManyField(blank=True, to='quiz.Quiz'),
        ),
    ]
