# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='profile', to='wiki.Subject'),
        ),
    ]
