# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20170221_0431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='study',
            field=models.CharField(choices=[(1, 'Datateknologi - 5 årig master'), (2, 'Datateknologi - 2 årig master')], default='dragvoll', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='year',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)], default='0'),
        ),
    ]
