# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-05 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_auto_20170302_1334'),
        ('profiles', '0003_auto_20170221_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subjects',
            field=models.ManyToManyField(to='wiki.Subject'),
        ),
    ]
