# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-06 18:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profile_subjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='study',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='year',
        ),
    ]
