# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-06 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20170306_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='profile', to='wiki.Subject'),
        ),
    ]
